[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "xaml-parser"
version = "0.1.0"
authors = [
    {name = "rpax contributors", email = "noreply@example.com"}
]
description = "Standalone XAML workflow parser for automation projects"
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.9"
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Text Processing :: Markup :: XML",
    "Topic :: Office/Business :: Office Suites",
]
keywords = ["xaml", "workflow", "automation", "parsing", "rpa"]

# Minimal dependencies for standalone package (ADR-015)
dependencies = [
    "defusedxml>=0.7.1",  # Security for XML parsing
    "pytest>=7.4",       # Testing framework for uv run pytest
]

[project.optional-dependencies]
dev = [
    "pytest>=7.4",
    "pytest-cov>=4.1", 
    "black>=23.0",
    "isort>=5.12",
    "ruff>=0.1",
    "mypy>=1.7",
    "types-defusedxml",
]
test = [
    "pytest>=7.4",
    "pytest-cov>=4.1",
]

[dependency-groups]
test = [
    "pytest>=7.4",
    "pytest-cov>=4.1",
]

[project.urls]
Homepage = "https://github.com/rpapub/rpax"
Repository = "https://github.com/rpapub/rpax"
Issues = "https://github.com/rpapub/rpax/issues"

[tool.setuptools]
package-dir = {"" = "."}

[tool.setuptools.packages.find]
where = ["."]
include = ["xaml_parser*"]

[tool.black]
line-length = 88
target-version = ['py39']

[tool.ruff]
line-length = 88
target-version = "py39"

[tool.mypy]
python_version = "3.9"
warn_return_any = true
warn_unused_configs = true
disallow_untyped_defs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = "--verbose"
markers = [
    "slow: marks tests as slow (deselect with '-m \"not slow\"')",
    "integration: marks tests as integration tests",
    "corpus: marks tests that use corpus data"
]